### ISSUE TITLE
[Fix] 글 단건조회시 수정 사항

### ISSUE THREAD

**Issue by hongsy521** [MixInn/MixIn_BE#42]
**⭐ Issue : Fix**
글 단건조회시 수정 사항

**Description**

**Todo**
- [x] 글 조회 시에 닉네임 말고 userResponseDto로 들어가도록
- [x] 투표가 포함된 글에서 투표를 했으면 결과와 함께, 투표 결과를 안했으면 투표항목만 나오도록
- [x] 게시글 상세조회에서 로그인한 사용자가 북마크를 했는 지 안했는지 여부 알 수 있도록

**Reference(Optional) **
